MovieRental/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace MovieRental.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int YearReleased { get; set; }
        public string Director { get; set; }
        public int GenreID { get; set; }
        public bool IsCheckedOut { get; set; }

        public Movie() { }
        public Movie(SqlDataReader reader)
        {
            this.ID = (int)reader["ID"];
            this.Name = reader["Name"].ToString();
            this.YearReleased = (int)reader["YearReleased"];
            this.Director = reader["Director"].ToString();
            this.GenreID = (int)reader["GenreID"];
            this.IsCheckedOut = Convert.ToBoolean(reader["IsCheckedOut"]);
        }
    }
}

MovieRental/Controllers/MovieController.cs
using MovieRental.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieRental.Controllers
{
    public class MovieController : Controller
    {
        const string PathToMovieRentalDatabase = @"Server=localhost\SQLEXPRESS;Database=MovieRental;Trusted_Connection=True;";
        MovieServices movieServices = new MovieServices(PathToMovieRentalDatabase);

        public ActionResult Index()
        {
            return View(movieServices.GetAllMovies());
        }
        
        public ActionResult CreateMovie()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateMovie(FormCollection collection)
        {
            movieServices.CreateMovie(collection);
            return RedirectToAction("CRUDmovies");
        }

        public ActionResult EditMovie(int id)
        {
            return View(movieServices.GetOneMovieByID(id));
        }

        [HttpPost]
        public ActionResult EditMovie(FormCollection collection)
        {
            movieServices.EditMovie(collection);
            return RedirectToAction("CRUDmovies");
        }

        public ActionResult DeleteMovie(int id)
        {
            movieServices.DeleteMovie(id);
            return RedirectToAction("CRUDmovies");
        }

        //for Admin
        public ActionResult CRUDmovies()
        {
            return View(movieServices.GetAllMovies());
        }
    }
}

MovieRental/Controllers/RentalController.cs
using MovieRental.Services;
using MovieRental.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieRental.Controllers
{    
    public class RentalController : Controller
    {
        const string PathToMovieRentalDatabase = @"Server=localhost\SQLEXPRESS;Database=MovieRental;Trusted_Connection=True;";
        RentalServices rentalServices = new RentalServices(PathToMovieRentalDatabase);

        [HttpGet]
        public ActionResult CheckInMovie(int id)
        {
            rentalServices.CheckInMovie(id);
            return RedirectToAction("Index", "Movie");
        }

        public ActionResult CustomersForCheckout(int id)
        {

            return View(new CheckOutMovieViewModel(id));
        }

        public ActionResult CheckOutMovie(int movieId, int customerID)
        {
            rentalServices.CheckOutMovie(movieId, customerID);
            return RedirectToAction("Index", "Movie");
        }
    }
}

MovieRental/Views/Movie/CRUDmovies.cshtml
@model IEnumerable<MovieRental.Models.Movie>

<p>
    @Html.ActionLink("Create New", "CreateMovie")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Year Released
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            Genre
        </th>
        <th>
            Checked Out
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearReleased)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @switch (item.GenreID)
            {
                case 1:
                    <span>Horror</span>
                    break;
                case 2:
                    <span>Fantasy</span>
                    break;
                case 3:
                    <span>Action</span>
                    break;
                case 4:
                    <span>Comedy</span>
                    break;
                default:
                    <span>Nothing Here</span>
                    break;
            }
        </td>
        <td>
            @if (item.IsCheckedOut == true)
            {
                <span>True</span>
            }
            else if (item.IsCheckedOut == false)
            {
                <span>False</span>
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "EditMovie", new { id=item.ID }) |
            @Html.ActionLink("Delete", "DeleteMovie", new { id=item.ID })
        </td>
    </tr>
}

</table>

MovieRental/Views/Movie/CreateMovie.cshtml
@model MovieRental.Models.Movie

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearReleased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearReleased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearReleased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCheckedOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCheckedOut)
                    @Html.ValidationMessageFor(model => model.IsCheckedOut, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MovieRental/Views/Movie/EditMovie.cshtml
@model MovieRental.Models.Movie


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearReleased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearReleased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearReleased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCheckedOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCheckedOut)
                    @Html.ValidationMessageFor(model => model.IsCheckedOut, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MovieRental/Views/Movie/Index.cshtml
@model IEnumerable<MovieRental.Models.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Daily Ops - All Movies</h2>

<table class="table">
    <tr>
        <th>
            <span>ID</span>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            <span>Year Released</span>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            <span>Genre</span>
        </th>
        <th>
            <span>Checked Out</span>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearReleased)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @switch(item.GenreID)
                {
                    case 1:
                        <span>Horror</span>
                        break;
                    case 2:
                        <span>Fantasy</span>
                        break;
                    case 3:
                        <span>Action</span>
                        break;
                    case 4:
                        <span>Comedy</span>
                        break;
                    default:
                        <span>Nothing Here</span>
                        break;
            }
        </td>
        <td>
            @if(item.IsCheckedOut == true)
            {
                <span>True</span>
            } else if(item.IsCheckedOut == false)
            {
                <span>False</span>
            }
        </td>
        <td>
            @if(item.IsCheckedOut.ToString() == "True")
            {
                @Html.ActionLink("Check In", "CheckInMovie", "Rental", new { id = item.ID }, null);
            }
            else if(item.IsCheckedOut.ToString() == "False")
            {
                @Html.ActionLink("Check Out", "CustomersForCheckout", "Rental", new { id = item.ID }, null);
            }
        </td>
    </tr>
}

</table>